import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { cache } from "react";
import { supabaseAdmin } from "@/lib/supabase-admin";
import type { Lead } from "@/lib/supabase";
import { PreviewSite } from "./preview-site";

// Preview sites read fresh lead data on every request — a slug generated by
// this afternoon's cron must resolve immediately, never a cached 404.
export const dynamic = "force-dynamic";

const getPreviewLead = cache(async (slug: string) => {
  const { data } = await supabaseAdmin
    .from("leads")
    .select("*")
    .eq("preview_slug", slug)
    .maybeSingle();
  const lead = data as Lead | null;
  if (!lead?.generated_site) return null;
  return lead;
});

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const lead = await getPreviewLead((await params).slug);
  // Preview sites must never rank against (or as) the client's business.
  const robots = { index: false, follow: false };
  if (!lead?.generated_site) return { robots };
  const site = lead.generated_site;
  return {
    title: `${site.businessName}${site.city ? ` — ${site.city}, CA` : ""}`,
    description: site.tagline,
    robots,
  };
}

export default async function PreviewPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const lead = await getPreviewLead((await params).slug);
  if (!lead?.generated_site) notFound();
  return <PreviewSite site={lead.generated_site} />;
}
